[workspace]

members = [
    "days/day_1/jamie",
    "days/day_2/jamie",
    "days/day_3/jamie",
    "days/day_4/jamie",
    "days/day_5/jamie",
    "days/day_7/jamie",
    "days/day_8/jamie",
    "days/day_9/jamie",
    "days/day_10/jamie"
    ]
